/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "packet.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Audio, Audio, AUTO)


PB_BIND(Text, Text, AUTO)


PB_BIND(Command, Command, AUTO)


PB_BIND(DeviceInfo, DeviceInfo, AUTO)


PB_BIND(Packet, Packet, AUTO)


PB_BIND(Packet_Head, Packet_Head, AUTO)







