/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PACKET_PB_H_INCLUDED
#define PB_PACKET_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MessageType {
    MessageType_MESSAGE_TYPE_AUDIO = 0,
    MessageType_MESSAGE_TYPE_TEXT = 1,
    MessageType_MESSAGE_TYPE_COMMAND = 2
} MessageType;

typedef enum _Commands {
    Commands_COMMANDS_CLEAR_HISTORY = 1
} Commands;

/* Struct definitions */
typedef struct _Audio {
    pb_callback_t data;
    uint32_t sample_rate;
    uint32_t channels;
} Audio;

typedef struct _Text {
    pb_callback_t text;
} Text;

typedef struct _Command {
    Commands command;
} Command;

typedef struct _DeviceInfo {
    bool has_display_height;
    int32_t display_height;
    bool has_display_width;
    int32_t display_width;
    bool has_play_sample_rate;
    uint32_t play_sample_rate;
    bool has_play_bps;
    uint32_t play_bps;
    bool has_play_channels;
    uint32_t play_channels;
} DeviceInfo;

typedef struct _Packet_Head {
    int32_t version;
    MessageType type;
    bool has_device_info;
    DeviceInfo device_info;
} Packet_Head;

typedef struct _Packet {
    Packet_Head head;
    pb_size_t which_body;
    union {
        Audio audio;
        Text text;
        Command command;
    } body;
} Packet;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MessageType_MIN MessageType_MESSAGE_TYPE_AUDIO
#define _MessageType_MAX MessageType_MESSAGE_TYPE_COMMAND
#define _MessageType_ARRAYSIZE ((MessageType)(MessageType_MESSAGE_TYPE_COMMAND+1))

#define _Commands_MIN Commands_COMMANDS_CLEAR_HISTORY
#define _Commands_MAX Commands_COMMANDS_CLEAR_HISTORY
#define _Commands_ARRAYSIZE ((Commands)(Commands_COMMANDS_CLEAR_HISTORY+1))



#define Command_command_ENUMTYPE Commands



#define Packet_Head_type_ENUMTYPE MessageType


/* Initializer values for message structs */
#define Audio_init_default                       {{{NULL}, NULL}, 0, 0}
#define Text_init_default                        {{{NULL}, NULL}}
#define Command_init_default                     {_Commands_MIN}
#define DeviceInfo_init_default                  {false, 0, false, 0, false, 0, false, 0, false, 0}
#define Packet_init_default                      {Packet_Head_init_default, 0, {Audio_init_default}}
#define Packet_Head_init_default                 {0, _MessageType_MIN, false, DeviceInfo_init_default}
#define Audio_init_zero                          {{{NULL}, NULL}, 0, 0}
#define Text_init_zero                           {{{NULL}, NULL}}
#define Command_init_zero                        {_Commands_MIN}
#define DeviceInfo_init_zero                     {false, 0, false, 0, false, 0, false, 0, false, 0}
#define Packet_init_zero                         {Packet_Head_init_zero, 0, {Audio_init_zero}}
#define Packet_Head_init_zero                    {0, _MessageType_MIN, false, DeviceInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Audio_data_tag                           1
#define Audio_sample_rate_tag                    2
#define Audio_channels_tag                       3
#define Text_text_tag                            1
#define Command_command_tag                      1
#define DeviceInfo_display_height_tag            1
#define DeviceInfo_display_width_tag             2
#define DeviceInfo_play_sample_rate_tag          3
#define DeviceInfo_play_bps_tag                  4
#define DeviceInfo_play_channels_tag             5
#define Packet_Head_version_tag                  1
#define Packet_Head_type_tag                     2
#define Packet_Head_device_info_tag              3
#define Packet_head_tag                          1
#define Packet_audio_tag                         2
#define Packet_text_tag                          3
#define Packet_command_tag                       4

/* Struct field encoding specification for nanopb */
#define Audio_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    data,              1) \
X(a, STATIC,   REQUIRED, UINT32,   sample_rate,       2) \
X(a, STATIC,   REQUIRED, UINT32,   channels,          3)
#define Audio_CALLBACK pb_default_field_callback
#define Audio_DEFAULT NULL

#define Text_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   text,              1)
#define Text_CALLBACK pb_default_field_callback
#define Text_DEFAULT NULL

#define Command_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    command,           1)
#define Command_CALLBACK NULL
#define Command_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

#define DeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    display_height,    1) \
X(a, STATIC,   OPTIONAL, INT32,    display_width,     2) \
X(a, STATIC,   OPTIONAL, UINT32,   play_sample_rate,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   play_bps,          4) \
X(a, STATIC,   OPTIONAL, UINT32,   play_channels,     5)
#define DeviceInfo_CALLBACK NULL
#define DeviceInfo_DEFAULT NULL

#define Packet_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  head,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,audio,body.audio),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,text,body.text),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,command,body.command),   4)
#define Packet_CALLBACK NULL
#define Packet_DEFAULT NULL
#define Packet_head_MSGTYPE Packet_Head
#define Packet_body_audio_MSGTYPE Audio
#define Packet_body_text_MSGTYPE Text
#define Packet_body_command_MSGTYPE Command

#define Packet_Head_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    version,           1) \
X(a, STATIC,   REQUIRED, UENUM,    type,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       3)
#define Packet_Head_CALLBACK NULL
#define Packet_Head_DEFAULT NULL
#define Packet_Head_device_info_MSGTYPE DeviceInfo

extern const pb_msgdesc_t Audio_msg;
extern const pb_msgdesc_t Text_msg;
extern const pb_msgdesc_t Command_msg;
extern const pb_msgdesc_t DeviceInfo_msg;
extern const pb_msgdesc_t Packet_msg;
extern const pb_msgdesc_t Packet_Head_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Audio_fields &Audio_msg
#define Text_fields &Text_msg
#define Command_fields &Command_msg
#define DeviceInfo_fields &DeviceInfo_msg
#define Packet_fields &Packet_msg
#define Packet_Head_fields &Packet_Head_msg

/* Maximum encoded size of messages (where known) */
/* Audio_size depends on runtime parameters */
/* Text_size depends on runtime parameters */
/* Packet_size depends on runtime parameters */
#define Command_size                             2
#define DeviceInfo_size                          40
#define PACKET_PB_H_MAX_SIZE                     Packet_Head_size
#define Packet_Head_size                         55

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
